### ISSUE TITLE
Climate data

### ISSUE THREAD

**Issue by kone-colab** [gicait/PyAEZ#1]
I would like to know if it is possible to use the PyAEZ with only temperatures and precipitation. In my region, the other variables (shortwave radiation, wind speed, relative humidity) cited in the documentation are missing

**Comment by lakmalnd** [comment]
You can obtain these datasets from global datasets like "TerraClimate". Shortwave radiation is important parameters. So better to include that. And for wind speed and relative humidity, you can assume reasonable constant value for your study area.
