### ISSUE TITLE
Evaluating crop suitability index under different input levels

### ISSUE THREAD

**Issue by KaixuanDai** [gicait/PyAEZ#119]
Hello! Thank you for your attention and support! 
I want to try to evaluate the crop **suitability index** and **potential maximum yield** under different **input levels** using PyAEZ, but I have some questions as:

1. Is it sufficient to modify the crop parameters in the [input_crop_TSUM_parameters_maiz_sugar.csv](https://github.com/gicait/PyAEZ/blob/5575ecfe0872fd66fea9eaeea9c13b84a3720441/data_input/input_crop_TSUM_parameters_maiz_sugar.xlsx) file to distinct the input level?

2. I noticed that currently, only maps of suitability level distribution can be output. I would like to know if it is possible to calculate the suitability index directly according to the formulas in the GAEZ model document as below.
![image](https://github.com/gicait/PyAEZ/assets/37492695/885ed2f7-5d4c-42dc-b890-849d64f6654c)

Thank you!

**Comment by NokuzaSezo97** [comment]
Hi @KaixuanDai,

Answer for Q1: Yes, you can modify crop parameters based on your input-level/management.

Answer for Q2: Technically, yes, you can. In PyAEZ under UtilitiesCalc module, there's a function classifying maximum attainable yield into six suitability classes (mentioned in the clipped figure). You only need to implement 3 x 3 kernal distribution of all six classes and apply SI formula.

Regards,

Swun Wunna Htet

**Comment by KaixuanDai** [comment]
Thanks for your patient answer. 

It is an intelligent to calculate the SI by the kernal window (I thought it is an aggragation from low resolution pixels to larger pixel before)

For the setting of input-level/management, I now understand it depends on the **soil quality/soil rating** and the **crop parameters**. 

When we want to evaluate the different input-level/management, we only need to adjust :
1. the parameter in calculateSoilQualities (irr/rain) calculateSoilRatings(H/L/I)
2. the crop parameters

This is my rough understanding, please criticize and correct :)

**Comment by NokuzaSezo97** [comment]
@KaixuanDai,

You're correct. However, as v2.2 Soil Constraint is still experimental (meaning the validation is in progress), the obtained fc4 will not be correct. I would suggest to use V2.0 Module IV for your soil constraint evaluation.

Regards,

Swun Wunna Htet

**Comment by KaixuanDai** [comment]
I see, thanks for your suggestions!
