### ISSUE TITLE
error in NB2 aez.readCropandCropCycleParameters

### ISSUE THREAD

**Issue by handuGIS** [gicait/PyAEZ#124]
hi, there is an error. When I run the aez.readCropandCropCycleParameters. I set these index as nan, but the optional thermal screening function is still activated. 

![屏幕截图 2024-04-01 161307](https://github.com/gicait/PyAEZ/assets/165275173/cf6f4e69-5c90-41ce-a7f7-0bdd54f74470)
![屏幕截图 2024-04-01 161624](https://github.com/gicait/PyAEZ/assets/165275173/b786d763-8fe6-41dd-8694-ff29d628492f)

**Comment by NokuzaSezo97** [comment]
Hi @handuGIS,

Instead of setting nan as **#N/A**, just **nan** will do. Hope this helps.

Swun Wunna Htet

**Comment by handuGIS** [comment]
hi @NokuzaSezo97,  I took your advice, but the same error still exists

**Comment by NokuzaSezo97** [comment]
Hi @handuGIS,

I just tested and discovered a minor bug which the thermal screening flag is activated even when the threshold values are not provided, thus encountering this error. I'll fix this bug immediately. Kindly redownload or clone the master repository tomorrow for accessing the revised version. My sincere apologies for the delay.

Regards,

Swun Wunna Htet

**Comment by handuGIS** [comment]
ok! thank you very much for your reply. Hope you solve this bug smoothly.
