### ISSUE TITLE
NB2 | i1 = np.where(yield_of_all_crop_cycles_rainfed == np.max(yield_of_all_crop_cycles_rainfed))[0][0] # index of maximum yield

### ISSUE THREAD

**Issue by maobw12** [gicait/PyAEZ#136]
When I run NB2, it runs up to 9% with an error as shown below. which aspect should I check?
Does the reported error mean that there is a problem with a particular raster while traversing the raster? 
![1718623224354](https://github.com/gicait/PyAEZ/assets/151036992/19d3b868-2cba-4539-b118-8871d3d1261f)

**Comment by handuGIS** [comment]
I have the same erro, could you please tell me how did you solve this problem?
