### ISSUE TITLE
Issue about the ETa in the "getLGP_G_5_and_10" function

### ISSUE THREAD

**Issue by Saibo-Li** [gicait/PyAEZ#15]
https://github.com/gicait/PyAEZ/blob/5ca84abe7311e9e79495da2ebb6fb53dc3c9c60c/pyaez/ClimateRegime.py#L352

Based on page 28 of the model document ([Global Agro-Ecological Zones v4 – Model documentation.pdf](https://www.fao.org/3/cb4744en/cb4744en.pdf)), ETa = ETm, when P > ETm or when P < ETm but P+Wb-Wr > ETm.

But the this line 375,  _**”self.totalPrec_daily[i_r,i_c,ii] + W >= Sa*D*(1-pc)“**_ is only **_P+Wb >= Wr_**,  not meets **_"P+Wb-Wr > ETm"_**. https://github.com/gicait/PyAEZ/blob/5ca84abe7311e9e79495da2ebb6fb53dc3c9c60c/pyaez/ClimateRegime.py#L375

**Comment by kboonma** [comment]
Dear @Saibo-Li, the current team of developers are not sure if that was a numerical trick or an actual glitch in the code from the previous version. We are glad to share the news that we are releasing PyAEZ version 2 at the end of November 2022, and this specific issue you raised had already been fixed, the source codes now should follow the GAEZv4 Documentation (within the PyAEZ extent) and are more readable/understandable. An updated PyAEZv2 Documentation will also be released.

**Comment by Saibo-Li** [comment]
Dear @kboonma, many thanks to you and your team. We're looking forward to this latest version. However, we really want to use this _getLGP_G_5_and_10_ function recently, I wonder if you can only share the ClimateRegime.py (or this function ). My email is seibertli602@gmail.com?  We are sorry for this rude request!

**Comment by kboonma** [comment]
@Saibo-Li I sent you some fixes as requested. Please consider registering for the upcoming official PyAEZ launching event and technical training.

**Comment by Saibo-Li** [comment]
Thank you very much! I have registered. The official launch event and technical training are very helpful to me!
