### ISSUE TITLE
How to get the terrain_factor in Module 5

### ISSUE THREAD

**Issue by colormeblue1013** [gicait/PyAEZ#92]
Hi, 

Thanks for your amazing work! I'm just a little bit confused about how to get the Terrain_factor in Module 5. For irrigated-intermediate input-wetland rice, there seems to be a mismatch between the values in **ALL_REDUCTION_FACTORS.py** and the numbers in **Table A6-8.2 in GAEZ 4.0** documentation.

Best Regards,
Yang

**Comment by colormeblue1013** [comment]
![mmexport1699596025890.png](https://github.com/gicait/PyAEZ/assets/71979368/f242512e-fa2e-4a8e-ba8d-fefd7aed143b)
![mmexport1699596028383.jpg](https://github.com/gicait/PyAEZ/assets/71979368/6cc092a1-47a9-443f-aff5-0507039af70c)

**Comment by NokuzaSezo97** [comment]
Hi @colormeblue1013,

Sorry for the late reply. Yes, some of the reduction factors set up in tutorial files won't be the same as GAEZ appendices, as these settings are localized values, specifically to Laos in this case. You can fully refer to **GAEZ documentation** values stated in your highlighted screenshot in your terrain constraint analysis. **Alternatively**, if you have local knowledge of how influential the yield reduction's going to be in your area interest, the settings can also be set up different from GAEZ database. If this's the case, please check out the concept behind the terrain constraints, and apply factors accordingly.

Regards,

Swun Wunna Htet

**Comment by colormeblue1013** [comment]
Many thanks for your kind reply! I think we'll refer to GAEZ documentation for now and leave the localization settings for future work.
